# Generated by Django 3.2.16 on 2022-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='filamentType',
            field=models.CharField(default='', max_length=100),
        ),
    ]
