# Generated by Django 3.2.16 on 2022-11-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20221129_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('color', models.CharField(default='', max_length=100)),
                ('filamentType', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('manufacturer', models.CharField(default='', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
