# Generated by Django 3.2.16 on 2022-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20221129_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='pathToImg',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
