# Generated by Django 3.2.16 on 2022-12-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_position_pathtoimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=255)),
                ('propertyValue', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.category')),
            ],
        ),
    ]
