# Generated by Django 3.2.16 on 2022-12-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_categoryvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryvalue',
            name='data',
            field=models.JSONField(default=''),
        ),
    ]
