# Generated by Django 3.2.16 on 2022-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_categoryvalue_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryvalue',
            name='data',
        ),
        migrations.RemoveField(
            model_name='position',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='position',
            name='color',
        ),
        migrations.RemoveField(
            model_name='position',
            name='filamentType',
        ),
        migrations.RemoveField(
            model_name='position',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='position',
            name='pathToImg',
        ),
        migrations.RemoveField(
            model_name='position',
            name='price',
        ),
        migrations.AddField(
            model_name='position',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
