# Generated by Django 3.2.16 on 2022-12-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20221211_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
