# Generated by Django 3.2.16 on 2023-01-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20230109_1821'),
        ('warehouse', '0013_auto_20230109_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
