# Generated by Django 3.2.16 on 2023-01-22 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='to_pay_gross',
            new_name='cost_gross',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='to_pay_net',
            new_name='cost_net',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=datetime.date(2023, 1, 22)),
        ),
    ]
